#!/usr/bin/perl
use strict;
open(my $dict,">",'dict.h');
print $dict "#ifndef DICTIONARY_H\
#define DICTIONARY_H\
#include \"stack.h\"\n";
for (@ARGV) {
	print $dict "#include \"$_\"\n";
	open(my $file,'<',$_) or die "$_ does not exist\n";
	while (my $line = <$file>) {
		$line=~/core\((.*),([0-9]+)\) ([^(]+)/ or next;
		print $dict "void s_",lc $1,"() {push($3(";
		for (1..$2) {
			print $dict "pop()";
			print $dict "," if ($_<$2);
		}
		print $dict "));}\n";
	}
	close($file);
}
print $dict "#endif\n";
close($dict);
