#!/usr/bin/perl
use strict;
open(my $dict,">",'dict.h');
print $dict "#ifndef DICTIONARY_H\
#define DICTIONARY_H\
#include \"stack.h\"\n";
my @alphabet=('a'..'z');
for (@ARGV) {
	print $dict "#include \"$_\"\n";
	open(my $file,'<',$_) or die "$_ does not exist\n";
	while (my $line = <$file>) {
		my ($lname,$argc,$cname)=($line=~/core\((.*),([0-9]+)\) ([^(]+)/g) or next;
		print $dict "void s_",lc $lname,"() {\n";
		print $dict "\tobj_t *$_=pop();\n" for (@alphabet[0..$argc-1]);
		print $dict "\tpush($cname(";
		for (0..$argc-1) {
			print $dict $alphabet[$argc-1-$_];
			print $dict ',' if ($_<$argc-1);
		}
		print $dict "));\n";
		print $dict "\tdec_rc($alphabet[$argc-1-$_]);\n" for (0..$argc-1);
		print $dict "}\n";
	}
	close($file);
}
print $dict "#endif\n";
close($dict);
